<!DOCTYPE html>
<html lang="es"><head><meta name="csrf-token" content="{{ csrf_token() }}"><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Mi Portal | IRIS</title><link rel="stylesheet" href="{{ asset('css/global.css') }}"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/auxilio.css') }}"><link rel="stylesheet" href="{{ asset('css/sidebar.css') }}"><link rel="stylesheet" href="{{ asset('css/iris-backend.css') }}"></head>
<body class="dashboard-body"><div id="menu-dinamico"></div><script src="{{ asset('js/menu-paciente.js') }}"></script><main class="dashboard-main">@include('partials.paciente-header', ['title'=>'Hola, '.auth()->user()->nombre, 'subtitle'=>'Este es tu panel de seguimiento real dentro de IRIS.'])@include('partials.frontend-alerts')
<section class="stats-grid"><article class="stat-card"><span>Próximas citas</span><strong>{{ $appointments->whereIn('status', ['accepted','pending','paid'])->count() }}</strong></article><article class="stat-card"><span>Tareas activas</span><strong>{{ $tasks->where('status', '!=', 'completada')->count() }}</strong></article><article class="stat-card"><span>Notificaciones</span><strong>{{ auth()->user()->unreadNotifications()->count() }}</strong></article></section>
<section class="dashboard-grid">
  <article class="dash-card appointment-card"><div class="card-top"><div><h2>Próximas citas</h2><p class="card-subtitle">Citas reales registradas en la base de datos.</p></div><a class="btn-outline btn-sm" href="{{ route('paciente.gestion-citas') }}">Ver todas</a></div>
  <div class="appointment-list">@forelse($appointments as $appointment)<div class="appointment-row"><span class="appt-avatar">{{ $appointment->professional?->initials() ?? 'IR' }}</span><div class="appt-info"><strong>{{ $appointment->professional?->nombre_completo ?? 'Especialista pendiente' }}</strong><span>{{ $appointment->reason }} · {{ $appointment->modality }} · {{ $appointment->status }}</span></div><span class="appt-time">{{ optional($appointment->starts_at)->format('d/m H:i') ?? 'Por definir' }}</span></div>@empty<div class="backend-empty">Aún no tienes citas registradas.</div>@endforelse</div></article>
  <article class="dash-card"><div class="card-top"><div><h2>Tareas terapéuticas</h2><p class="card-subtitle">Actividades asignadas por tus profesionales.</p></div><a class="btn-outline btn-sm" href="{{ route('paciente.mis-tareas') }}">Ver tareas</a></div><div class="task-list">@forelse($tasks as $task)<div class="task-item"><strong>{{ $task->title }}</strong><p>{{ \Illuminate\Support\Str::limit($task->description, 120) }}</p><span class="backend-chip {{ $task->status === 'completada' ? '' : 'warn' }}">{{ $task->status }}</span></div>@empty<div class="backend-empty">No tienes tareas asignadas.</div>@endforelse</div></article>
  <form method="POST" action="{{ route('paciente.diario.store') }}" class="dash-card diary-card">@csrf<div class="card-top"><div><h2>Entrada rápida de diario</h2><p class="card-subtitle">Guarda una nota emocional del día.</p></div></div><textarea class="diary-textarea" name="content" required placeholder="¿Cómo te sientes hoy?"></textarea><input type="hidden" name="title" value="Entrada rápida"><div class="diary-actions"><button class="btn-primary" type="submit">Guardar</button><a class="btn-outline" href="{{ route('paciente.diario') }}">Abrir diario</a></div></form>
  <article class="dash-card"><div class="card-top"><div><h2>Comunidad</h2><p class="card-subtitle">Espacio moderado de apoyo.</p></div></div><p>Comparte experiencias o lee publicaciones de otros usuarios desde un entorno con reglas de convivencia.</p><a class="btn-primary" href="{{ route('comunidad.index') }}">Ir a comunidad</a></article>
</section></main>@include('partials.floating-auxilio')</body></html>
