<!DOCTYPE html>
<html lang="es"><head><meta name="csrf-token" content="<?php echo e(csrf_token()); ?>"><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Mi Portal | IRIS</title><link rel="stylesheet" href="<?php echo e(asset('css/global.css')); ?>"><link rel="stylesheet" href="<?php echo e(asset('css/dashboard.css')); ?>"><link rel="stylesheet" href="<?php echo e(asset('css/auxilio.css')); ?>"><link rel="stylesheet" href="<?php echo e(asset('css/sidebar.css')); ?>"><link rel="stylesheet" href="<?php echo e(asset('css/iris-backend.css')); ?>"></head>
<body class="dashboard-body"><div id="menu-dinamico"></div><script src="<?php echo e(asset('js/menu-paciente.js')); ?>"></script><main class="dashboard-main"><?php echo $__env->make('partials.paciente-header', ['title'=>'Hola, '.auth()->user()->nombre, 'subtitle'=>'Este es tu panel de seguimiento real dentro de IRIS.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php echo $__env->make('partials.frontend-alerts', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="stats-grid"><article class="stat-card"><span>Próximas citas</span><strong><?php echo e($appointments->whereIn('status', ['accepted','pending','paid'])->count()); ?></strong></article><article class="stat-card"><span>Tareas activas</span><strong><?php echo e($tasks->where('status', '!=', 'completada')->count()); ?></strong></article><article class="stat-card"><span>Notificaciones</span><strong><?php echo e(auth()->user()->unreadNotifications()->count()); ?></strong></article></section>
<section class="dashboard-grid">
  <article class="dash-card appointment-card"><div class="card-top"><div><h2>Próximas citas</h2><p class="card-subtitle">Citas reales registradas en la base de datos.</p></div><a class="btn-outline btn-sm" href="<?php echo e(route('paciente.gestion-citas')); ?>">Ver todas</a></div>
  <div class="appointment-list"><?php $__empty_1 = true; $__currentLoopData = $appointments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $appointment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="appointment-row"><span class="appt-avatar"><?php echo e($appointment->professional?->initials() ?? 'IR'); ?></span><div class="appt-info"><strong><?php echo e($appointment->professional?->nombre_completo ?? 'Especialista pendiente'); ?></strong><span><?php echo e($appointment->reason); ?> · <?php echo e($appointment->modality); ?> · <?php echo e($appointment->status); ?></span></div><span class="appt-time"><?php echo e(optional($appointment->starts_at)->format('d/m H:i') ?? 'Por definir'); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="backend-empty">Aún no tienes citas registradas.</div><?php endif; ?></div></article>
  <article class="dash-card"><div class="card-top"><div><h2>Tareas terapéuticas</h2><p class="card-subtitle">Actividades asignadas por tus profesionales.</p></div><a class="btn-outline btn-sm" href="<?php echo e(route('paciente.mis-tareas')); ?>">Ver tareas</a></div><div class="task-list"><?php $__empty_1 = true; $__currentLoopData = $tasks; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $task): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="task-item"><strong><?php echo e($task->title); ?></strong><p><?php echo e(\Illuminate\Support\Str::limit($task->description, 120)); ?></p><span class="backend-chip <?php echo e($task->status === 'completada' ? '' : 'warn'); ?>"><?php echo e($task->status); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="backend-empty">No tienes tareas asignadas.</div><?php endif; ?></div></article>
  <form method="POST" action="<?php echo e(route('paciente.diario.store')); ?>" class="dash-card diary-card"><?php echo csrf_field(); ?><div class="card-top"><div><h2>Entrada rápida de diario</h2><p class="card-subtitle">Guarda una nota emocional del día.</p></div></div><textarea class="diary-textarea" name="content" required placeholder="¿Cómo te sientes hoy?"></textarea><input type="hidden" name="title" value="Entrada rápida"><div class="diary-actions"><button class="btn-primary" type="submit">Guardar</button><a class="btn-outline" href="<?php echo e(route('paciente.diario')); ?>">Abrir diario</a></div></form>
  <article class="dash-card"><div class="card-top"><div><h2>Comunidad</h2><p class="card-subtitle">Espacio moderado de apoyo.</p></div></div><p>Comparte experiencias o lee publicaciones de otros usuarios desde un entorno con reglas de convivencia.</p><a class="btn-primary" href="<?php echo e(route('comunidad.index')); ?>">Ir a comunidad</a></article>
</section></main><?php echo $__env->make('partials.floating-auxilio', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></body></html>
<?php /**PATH C:\laragon\www\iris-escom\resources\views/paciente/dashboard-paciente.blade.php ENDPATH**/ ?>